version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"  # Map container port to host port
    environment:
      - PORT=7860
    volumes:
      - ./model:/app/model
      - ./flagged:/app/flagged

